# =========================== Basic Settings ===========================
# machine info
num_gpus_per_job: 8  # number of gpus each job need
num_cpus_per_job: 63  # number of cpus each job need
memory_per_job: 380  # memory requirement each job need
gpu_type: "nvidia-tesla-p100"

# data
dataset: imagenet1k
data_transforms: imagenet1k_basic
data_loader: imagenet1k_basic
dataset_dir: /share5/public/classification_data/imagenet1k
data_loader_workers: 62

# info
num_classes: 1000
image_size: 224
topk: [1, 5]
num_epochs: 100
print_freq: 50

# optimizer
optimizer: sgd
momentum: 0.9
weight_decay: 0.0001
nesterov: True

# lr
lr: 0.1
lr_scheduler: multistep
multistep_lr_milestones: [30, 60, 90]
multistep_lr_gamma: 0.1

# model profiling
profiling: [gpu]

# pretrain, resume, test_only
pretrained: ''
resume: ''
test_only: False

#
random_seed: 1995
batch_size: 1024
model: ''
reset_parameters: True



# =========================== Override Settings ===========================
log_dir: logs/
slimmable_training: True
bn_cal_batch_num: 5
calibrate_bn: true
cumulative_bn_stats: true
num_sample_training: 4
universally_slimmable_training: True
soft_target: True

#model settting
model: models.us_mobilenet_v2_uneven
width_mult: 1.0
search_space: exp8
search_space_num: 28
inplace_distill: True

#special for train alone
train_alone_tag: True
model_idx: 1


# Do not modify default width_mult_list if you want to load pre-trained model with calibrated BN. Instead add your test width (can be arbitrary in width_mult_range) to width_mult_list_test
width_mult_list: [0.25, 0.275, 0.3, 0.325, 0.35, 0.375, 0.4, 0.425, 0.45, 0.475, 0.5, 0.525, 0.55, 0.575, 0.6, 0.625, 0.65, 0.675, 0.7, 0.725, 0.75, 0.775, 0.8, 0.825, 0.85, 0.875, 0.9, 0.925, 0.95, 0.975, 1.0]
# uncomment here if you want to test other widths.
width_mult_list_test: [0.25, 0.5, 0.75, 1.0]
width_mult_range: [0.25, 1.0]
data_transforms: imagenet1k_mobile
num_gpus_per_job: 8
batch_size: 1024
lr: 0.5
lr_scheduler: linear_decaying
num_epochs: 250
# test pretrained
# test_only: True
# pretrained: logs/us_mobilenet_v2_calibrated.pt
